# Generated by Django 4.1.4 on 2023-05-12 05:40

from django.db import migrations

def create_groups(apps, schema_migration):
    User = apps.get_model('users', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    modifie_offer = Permission.objects.get(codename='modifie_offer')
    delete_comment = Permission.objects.get(codename='delete_comment')
    create_offer = Permission.objects.get(codename='create_offer')
    add_comment = Permission.objects.get(codename='add_comment')
    
    creator_permissions = [
        modifie_offer,
        delete_comment,
        create_offer,
        add_comment,
    ]
    
    creators = Group(name='creators')
    creators.save()
    
    creators.permissions.set(creator_permissions)

    subscribers = Group(name='subscribers')
    subscribers.save()
    subscribers.permissions.add(create_offer)
    subscribers.permissions.add(add_comment)
    
    visitors = Group(name='visitors')
    visitors.save()
    visitors.permissions.add(create_offer)
    visitors.permissions.add(add_comment)
    
    for user in User.objects.all():
        if user.role == 'CREATOR':
            creators.user_set.add(user)
        if user.role == 'SUBSCRIBER':
            subscribers.user_set.add(user)
        if user.role == 'VISITOR':
            visitors.user_set.add(user)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_groups)]
