# Generated by Django 4.1.4 on 2023-06-09 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("offers", "0001_initial"),
        ("favoris", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="offer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="favorite_offer",
                to="offers.offer",
            ),
        ),
    ]
